version: '3'

# volume config
volumes:
  mdb:
    driver_opts:
      o: bind
      type: none
      device: /home/adantas-/mariadb-db

  wpdb:
    driver_opts:
      o: bind
      type: none
      device: /home/adantas-/wordpress-db

##############################################################################

# network config

networks:
  inception_network:
    name: inception_network
    driver: bridge

###############################################################################

# services
services:

  main-nginx:
    image: inception-nginx:latest
    container_name: inception-nginx
    env_file:
      - .env
    environment:
      - SERVER_NAME
    ports:
      - 443:443
    build:
      args:
        - SERVER_NAME=${SERVER_NAME}
      context: requirements/nginx
      dockerfile: Dockerfile
    depends_on:
      - main-wp
    networks:
      - inception_network

  main-wp:
    image: inception-wp:latest
    container_name: inception-wp
    env_file:
      - .env
    environment:
      - SERVER_NAME
      - ROOT_USER
      - ROOT_PW
      - ROOT_MAIL
      - WP_USER
      - WP_MAIL
      - WP_PW
    build:
      args:
        - WP_USER=${WP_USER}
        - WP_PW=${WP_PW}
        - WP_MAIL=${WP_MAIL}
        - ROOT_MAIL=${ROOT_MAIL}
        - ROOT_PW=${ROOT_PW}
        - ROOT_USER=${ROOT_USER}
        - SERVER_NAME=${SERVER_NAME}
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - main-db
    volumes:
      - wpdb:/var/www/html
    networks:
      - inception_network

  main-db:
    image: inception-mdb:latest
    container_name: inception-mdb
    env_file:
      - .env
    environment:
      - WP_DB
      - WP_USER
      - WP_PW
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
      args:
        - WP_DB=${WP_DB}
        - WP_USER=${WP_USER}
        - WP_PW=${WP_PW}
    volumes:
      - mdb:/var/lib/mysql
    networks:
      - inception_network

  bonus-static:
    image: inception-static:latest
    container_name: inception-static
    ports:
      - 4000:4000
    build:
      context: requirements/bonus/static
      dockerfile: Dockerfile
    networks:
      - inception_network